/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
import type * as compareSaveErc20Sol from "./compareSaveERC20.sol";
export type { compareSaveErc20Sol };
export type { IERC20 } from "./IERC20";
export type { SaveERC20 } from "./SaveERC20";
