/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20Sol from "./ERC20.sol";
export * as compareSaveErc20Sol from "./compareSaveERC20.sol";
export { IERC20__factory } from "./IERC20__factory";
export { SaveERC20__factory } from "./SaveERC20__factory";
